version: "2"
services:
  nextcloud:
    image: linuxserver/nextcloud
    container_name: nextcloud
    environment:
      - PUID=${PUID} 
      - PGID=${PGID} 
      - TZ=${TZ}
    volumes:
      - ${CONFIG_PATH_NC}:/config
      - ${DATA_PATH_NC}:/data
    depends_on:
      - mariadb
    restart: unless-stopped
  mariadb:
    image: linuxserver/mariadb
    container_name: nextclouddb
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PW}
      - TZ=${TZ}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=${MYSQL_DB_PW}
    volumes:
      - $[CONFIG_PATH_DB}:/config
    restart: unless-stopped
  letsencrypt:
    image: linuxserver/letsencrypt
    container_name: letsencrypt
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=${PUID}
      - PGID=${PGID}
      - TZ=${TZ}
      - URL=${URL}
      - SUBDOMAINS=${SUBDOMAINS}
      - VALIDATION=${VALID}
      - EMAIL=${EMAIL}
    volumes:
      - ${CONFIG_PATH_LE}:/config
    ports:
      - ${PORT_HTTPS}:443
      - ${PORT_HTTP}:80
    restart: unless-stopped
